# Python tutorial

# Variables

A name that is used to denote something or a value is called a variable. In python, variables can be declared and values can be assigned to it as follows,

In [176]:
x = 2
y = 5
z = 'Hey'

In [177]:
print(x+y, z)

7 Hey


Multiple variables can be assigned with the same value.

In [178]:
x = y = 1

In [179]:
print(x,y)

1 1


# Operators

## Arithmetic Operators

| Symbol | Task Performed |
|----|---|
| +  | Addition |
| -  | Subtraction |
| /  | division |
| %  | mod |
| *  | multiplication |
| **  | to the power of |

In [180]:
1+2

3

In [181]:
2-1

1

In [182]:
1*2

2

In [183]:
1/2

0.5

In [184]:
15%10

5

What is the operation %? It is called modulus and calculates the residual of dividing two numbers. For example

$$
15 = 10*1 + 5
$$

The residual of dividing 15 over 10 is 5, and therefore 15%10 = 5.

In [185]:
3**2

9

## Relational Operators

| Symbol | Task Performed |
|----|---|
| == | True, if it is equal |
| !=  | True, if not equal to |
| < | less than |
| > | greater than |
| <=  | less than or equal to |
| >=  | greater than or equal to |

In [186]:
z = 1
z

1

In [187]:
z == 1

True

In [188]:
z > 1

False

# Print Statement

The **print** statement can be used in the following different ways :

    - print("Hello World")
    - print("Hello", <Variable Containing the String>)
    - print("Hello" + <Variable Containing the String>)
    - print("Hello %s" % <variable containing the string>)

In [189]:
print("Hello World")

Hello World


Strings can be assigned to any variable.

In [190]:
string1 = 'World'
print('Hello', string1)

string2 = '!'
print('Hello', string1, string2)

Hello World
Hello World !


String concatenation is the "addition" of two strings. Observe that while concatenating there will be no space between the strings.

In [191]:
print('Hello' + string1 + string2)

HelloWorld!


# Data Structures

## Lists

Lists are the most commonly used data structure. They are sequences of data that are enclosed in square brackets and data are separated by a comma. Each of these data can be accessed by calling it's index value.

Lists are declared by just equating a variable to '[ ]' or list.

In [192]:
a = []

In [193]:
print(type(a))

<class 'list'>


One can directly assign the sequence of data to a list x as shown.

In [194]:
x = ['apple', 'orange']

### Indexing

In python, Indexing starts from 0. The list x, will have apple at index 0 and orange at index 1.

In [195]:
x[0]

'apple'

Indexing can also be done in reverse order. That is the last element can be accessed first. Here, indexing starts from -1. Thus index value -1 will be orange and index -2 will be apple.

In [196]:
x[-1]

'orange'

As you might have already guessed, x[0] = x[-2], x[1] = x[-1]. This concept can be extended towards lists with more many elements.

### Slicing

Indexing was only limited to accessing a single element, Slicing on the other hand is accessing a sequence of data inside the list. In other words "slicing" the list.

Slicing is done by defining the index values of the first element and the last element from the parent list that is required in the sliced list. It is written as parentlist[ a : b ] where a,b are the index values from the parent list. If a or b is not defined then the index value is considered to be the first value for a if a is not defined and the last value for b when b is not defined.

In [197]:
num = [0,1,2,3,4,5,6,7,8,9]

In [198]:
print(num[0:4])
print(num[4:])

[0, 1, 2, 3]
[4, 5, 6, 7, 8, 9]


You can also slice a list with a certain step between numbers.

In [199]:
num[:9:3]

[0, 3, 6]

### Built in List Functions

There are some built-in functions for lists.

To find the length of the list or the number of elements in a list, **len( )** is used.

In [200]:
len(num)

10

If the list contains numbers then **min( )** and **max( )** gives the minimum and maximum value in the list.

In [201]:
min(num)

0

In [202]:
max(num)

9

Function **sum()** sums all the elements in the list

In [203]:
sum(num)

45

Lists can be concatenated by adding, '+' them. The resultant list will contain all the elements of the lists that were added.

In [204]:
[1,2,3] + [5,4,7]

[1, 2, 3, 5, 4, 7]

Consider the below list.

In [205]:
names = ['Earth','Air','Fire','Water']

We want to check if 'Fire' and 'Wind' are present in the list names. In python you can use 'a in b' concept which would return 'True' if a is present in b and 'False' if not.

In [206]:
'Fire' in names

True

In [207]:
'Wind' in names

False

**append( )** is used to add a element at the end of the list.

In [208]:
lst = [1,1,4,8,7]

In [209]:
lst.append(1)
print(lst)

[1, 1, 4, 8, 7, 1]


**append( )** function can also be used to add a entire list at the end. Observe that the resultant list becomes a nested list.

In [210]:
lst1 = [5,4,2,8]

In [211]:
lst.append(lst1)
print(lst)

[1, 1, 4, 8, 7, 1, [5, 4, 2, 8]]


If we want to  concatenate the two lists we can also use the function **extend( )**.

In [212]:
lst = [1,1,4,8,7]
lst.extend(lst1)
print(lst)

[1, 1, 4, 8, 7, 5, 4, 2, 8]


**count( )** is used to count the number of times a particular element appears in a list. 

In [213]:
lst.count(1)

2

**index( )** is used to find the index value of a particular element. Note that if there are multiple elements of the same value then the first index value of that element is returned.

In [214]:
lst.index(1)

0

**insert(x,y)** is used to insert a element y at a specified index value x.

In [215]:
lst.insert(5, 'name')
print(lst)

[1, 1, 4, 8, 7, 'name', 5, 4, 2, 8]


**insert(x,y)** inserts but does not replace element. If you want to replace the element with another element you simply assign the value to that particular index.

In [216]:
lst[5] = 'Python'
print(lst)

[1, 1, 4, 8, 7, 'Python', 5, 4, 2, 8]


The entire elements present in the list can be reversed by using the **reverse()** function.

In [217]:
lst.reverse()
print(lst)

[8, 2, 4, 5, 'Python', 7, 8, 4, 1, 1]


Python offers built in operation **sort( )** to arrange the elements in ascending order.

In [218]:
lst = [1,5,7,2,3,0,1]
lst.sort()
print(lst)

[0, 1, 1, 2, 3, 5, 7]


For descending order, By default the reverse condition will be False for reverse. Hence changing it to True would arrange the elements in descending order.

In [219]:
lst.sort(reverse=True)
print(lst)

[7, 5, 3, 2, 1, 1, 0]


<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b > Return the sum of the first 5 elements of the follwing list</div>

In [220]:
num = [1,0,26,18,1.3,16,2,14,12.6,11.1]
# Your code here

<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b > Now, sort the list in ascending order and return the sum of thefirst 3 values.</div>

In [221]:
# Your code here

<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b > Given two lists a and b, create a third list c containing the last elements ob a and b. </div>

In [222]:
a =[1,4,9]
b = [-2,-7,-1]
# Your code here

<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b > Return the second smalest number in the following list.</div>

In [223]:
num = [1,0,26,18,1.3,16,2,14,12.6,11.1]
# Your code here

## Sets

Sets are mainly used to eliminate repeated numbers in a sequence/list. They are also used to perform some standard set operations.

Sets are declared as set() which will initialize a empty set. Also set([sequence]) can be executed to declare a set with elements

In [224]:
set1 = set()
print(set1)

set()


In [225]:
set0 = set([1,2,2,3,3,4])
print(set0)

{1, 2, 3, 4}


elements 2,3 which are repeated twice are seen only once. Thus all the elements in a set are distinct.

### Built-in Functions

In [226]:
set1 = set([1,2,3])

In [227]:
set2 = set([2,3,4,5])

**union( )** function returns a set which contains all the elements of both the sets without repition.

In [228]:
set1.union(set2)

{1, 2, 3, 4, 5}

**intersection( )** function outputs a set which contains all the elements that are in both sets.

In [229]:
set1.intersection(set2)

{2, 3}

**difference( )** function ouptuts a set which contains elements that are in set1 and not in set2.

In [230]:
set1.difference(set2)

{1}

## Strings

Strings are ordered text based data which are represented by enclosing the same in single/double/triple quotes.

In [231]:
String0 = 'Tomorrow will rain'
String1 = "Tomorrow will rain"
String2 = '''Tomorrow will rain'''

In [232]:
print(String0 )
print(String1)
print(String2)

Tomorrow will rain
Tomorrow will rain
Tomorrow will rain


String Indexing and Slicing are similar to lists.

In [233]:
print(String0[4])
print(String0[4:])

r
rrow will rain


### Built-in Functions

**find( )** function returns the index value of the given data that is to found in the string. If it is not found it returns **-1**. Remember to not confuse the returned -1 for reverse indexing value.

In [234]:
print(String0.find('will'))
print(String0.find('am'))

9
-1


The returned index value is the index of the first element in the input data.

**capitalize( )** is used to capitalize the first element in the string.

In [235]:
String3 = 'observe the first letter in this sentence.'
print(String3.capitalize())

Observe the first letter in this sentence.


**lower( )** converts any capital letter to small letter.

In [236]:
print(String0)
print(String0.lower())

Tomorrow will rain
tomorrow will rain


**upper( )** converts any small letter to capital letter.

In [237]:
String0.upper()

'TOMORROW WILL RAIN'

**endswith( )** function is used to check if the given string ends with the particular character.

In [238]:
print(String0.endswith('y'))
print(String0.endswith('n'))

False
True


**count( )** function counts the number of times a character appears in a given string. The start and the stop index can also be specified or left blank.

In [239]:
print(String0.count('a',0))
print(String0.count('a',5,10))

1
0


**join( )** function can also be used to convert a list into a string.

In [240]:
a = list(String0)
print(a)
b = ''.join(a)
print(b)

['T', 'o', 'm', 'o', 'r', 'r', 'o', 'w', ' ', 'w', 'i', 'l', 'l', ' ', 'r', 'a', 'i', 'n']
Tomorrow will rain


**split( )** function is used to convert a string back to a list. It takes as an argument the separator it will use. Think of it as the opposite of the **join()** function.

In [241]:
d = b.split(' ')
print(d)

['Tomorrow', 'will', 'rain']


**replace( )** function replaces the element with another element.

In [242]:
String0.replace('Taj Mahal','Bengaluru')

'Tomorrow will rain'

**strip( )** function is used to delete blank spaces.

In [243]:
f = '    hello      '

If no char is specified then it will delete all the spacesin the right and left hand side of the data.

In [244]:
f.strip()

'hello'

<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b >Add the letters 'ing' to the following string.</div>

In [245]:
string = 'Train'
# Your code here

<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b >Remove the third letter of the following string.</div>

In [246]:
string = 'machine learning'
# Your code here

<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b >Lowercase the first 4 letters of the following string.</div>

In [247]:
string = 'MACHINE LEARNING'
#Your code here

## Dictionaries

Dictionaries are similar to data bases. They contain pairs of keys and values.

To define a dictionary, equate a variable to { } or dict()

In [248]:
d0 = {}
d1 = dict()
print(d0,d1)

{} {}


Dictionary are similar to lists, but the indexes have names. To add or replace a new element, instead of accessing with an index number(list[i]=...) you can give a name to such index (dict['name'] = 'Juan'). 

In [249]:
d0['Name'] = 'Juan'
d0['Age'] = 12 
print(d0)

{'Name': 'Juan', 'Age': 12}


That is how a dictionary looks like. You can access to a certain value by passing the key.

In [250]:
print(d0['Name'])

Juan


Two lists which are related can be merged to form a dictionary.

In [251]:
names = ['One', 'Two', 'Three', 'Four', 'Five']
numbers = [1, 2, 3, 4, 5]

**zip( )** function is used to combine two lists.

In [252]:
d2 = zip(names,numbers)
a1 = dict(d2)
print(a1)

{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}


### Built-in Functions

**clear( )** function is used to erase the entire dictionary.

In [253]:
a1.clear()
print(a1)

{}


**values( )** function returns a list with all the assigned values in the dictionary.

In [254]:
d2 = zip(names,numbers)
a1 = dict(d2)
a1.values()

dict_values([1, 2, 3, 4, 5])

**keys( )** function returns all the index or the keys to which contains the values that it was assigned to.

In [255]:
a1.keys()

dict_keys(['One', 'Two', 'Three', 'Four', 'Five'])

**items( )** is returns a list containing both the list but each element in the dictionary is inside a tuple. This is same as the result that was obtained when zip function was used.

In [256]:
a1.items()

dict_items([('One', 1), ('Two', 2), ('Three', 3), ('Four', 4), ('Five', 5)])

**pop( )** function is used to get the remove that particular element and this removed element can be assigned to a new variable. Only the value is stored, not the key.

In [257]:
a2 = a1.pop('Four')
print(a1)
print(a2)

{'One': 1, 'Two': 2, 'Three': 3, 'Five': 5}
4


<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b >Check if the key 'Six' is present in the following dictionary.</div>

In [258]:
a1 ={'One': 1, 'Two': 2, 'Three': 3, 'Five': 5}
#Your code here

# Control Flow Statements

## If

The if statement is used when we want to run a piece of code only if a condition is satisfied.  The syntax is the following:


if some_condition:
    
    algorithm

In [259]:
x = 12
if x >10:
    print("Hello")

Hello


## If-else

We can also specify what to do if the condition is NOT met.

if some_condition:
    
    algorithm
    
else:
    
    algorithm

In [260]:
x = 12
if x > 10:
    print("hello")
else:
    print("world")

hello


## if-elif

The elif command is used to specify an action when the first condition is not satisfied and a second condition is satisfied. 

if some_condition:
    
    algorithm

elif some_condition:
    
    algorithm

else:
    
    algorithm

In [261]:
x = 10
y = 12
if x > y:
    print("x>y")
elif x < y:
    print("x<y")
else:
    print("x=y")

x<y


## Loops

### For

The `for` command is used to go through all the elements in a list one by one.

for variable in something:
    
    algorithm

In [262]:
for i in range(5):
    print(i)

0
1
2
3
4


In the above example, i iterates over the 0,1,2,3,4. The range command generates a list of elements. You can specify the first element from the list, the last one and the step between them. By default, the first value is 0 and the step is 1. For example, the command range(0,1,0.1) will return the list [0, 0.1,...0.9].

Every time it takes each value and executes the algorithm inside the loop. It is also possible to iterate over a nested list:

In [263]:
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for list1 in list_of_lists:
        print(list1)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


If we want to iterate over the secondary list, we need two for loops:

In [264]:
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for list1 in list_of_lists:
    for x in list1:
        print(x)

1
2
3
4
5
6
7
8
9


### While

The algorithm inside the while loop is executed as long as some condition is satsfied.

while some_condition:
    
    algorithm

In [265]:
i = 1
while i < 3:
    print(i ** 2)
    i = i+1
print('Bye')

1
4
Bye


## Break

It is used to break out of a loop.

In [266]:
for i in range(100):
    print(i)
    if i>=7:
        break

0
1
2
3
4
5
6
7


## Continue

This continues the rest of the loop. It can be used to avoid applying a part of the algorithm in specific elements. If we reach a continue statement, we ignore this element and continue with the next element in the loop.

In [267]:
for i in range(10):
    if i>4:
        print("The end.")
        continue
    elif i<7:
        print(i)

0
1
2
3
4
The end.
The end.
The end.
The end.
The end.


## List Comprehensions

Python makes it simple to generate a list with a single line of code instead of using a for loop. For example, if you want to generate multiples of 27 and write them in a list, you could do the following:

In [268]:
res = []
for i in range(1,11):
    x = 27*i
    res.append(x)
print(res)

[27, 54, 81, 108, 135, 162, 189, 216, 243, 270]


List comprehensions is a more efficient way to solve this problem.

In [269]:
[27*x for x in range(1,11)]

[27, 54, 81, 108, 135, 162, 189, 216, 243, 270]

That's it!. Only remember to enclose it in square brackets

The first bit of code (in this case `27*x`) is the algorithm to calculate each element of the list. Then you write the loop.

 <div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b > Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included) and store them in a list. </div>


In [270]:
# Your code here
lst = [x for x in range(1500,2700) if(x%7==0 and x%5==0)]


 <div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b > Write a Python program that prints all the numbers from 0 to 6 except 3 and 6. Note: use the command continue. </div>


In [271]:
# Your code here

The Fibonacci sequence is a series of numbers where a number is the addition of the last two numbers, starting with 1, and 1.

Therefore, the first numbers of the Fibonacci series are: $1,1,2,3,5,8,13, 21, 34, 55, \cdots$

Mathematically, the Fibonacci numbers can be found with the following expression:

$$
x_{n} = x_{n-1} + x_{n-2}, \quad x_1 = 1, \ x_2 = 1
$$

The Fibonacci series has important applications in mathematics and natural sciences. For more information, see [this link](https://elearningindustry.com/fibonacci-sequence-what-is-and-how-applies-agile-development)
 
 <div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b > Find the first 20 numbers of the Fibonnaci series and write them in a list </div>

In [272]:
# Your code here

x1 = 1
x2 = 1
fib = [x1,x2]
for i in range(38):
    x3 = x2 + x1
    fib.append(x3)
    x1=x2
    x2=x3
    

# Functions

Most of the times we want to repeat an algorithm many times. We want to avoid copying and pasting the same code every time. One way to avoid that is by using functions.

This is the basic syntax of a function

def funcname(arg1, arg2,... argN):
    
    ''' Document String'''

    statements


    return <value>

Read the above syntax as, A function by name "funcname" is defined, which accepts arguements "arg1,arg2,....argN". The function is documented and it is '''Document String'''. The function after executing the statements returns a "value".

In [273]:
print("Hello Laia!")
print("Hey Laia, How do you do?")

Hello Laia!
Hey Laia, How do you do?


Instead of writing the above two statements every single time it can be replaced by defining a function which would do the job in just one line. 

Defining a function firstfunc().

In [274]:
def firstfunc():
    print("Hey Laia!")
    print("Hey Laia, How do you do?")   

In [275]:
firstfunc()

Hey Laia!
Hey Laia, How do you do?


**firstfunc()** every time just prints the message to a single person. We can make our function **firstfunc()** to accept arguements which will store the name and then print the sentence using that name. To do so, add a argument within the function.

In [276]:
def firstfunc(username):
    print("Hey", username + '!')
    print('Hey ' + username + ',' ,"How do you do?")

You can try passing your name to the function and see what happens.

In [277]:
firstfunc('Tino')

Hey Tino!
Hey Tino, How do you do?


## Return Statement

When the function results in some value and that value has to be stored in a variable or needs to be sent back or returned for further operation to the main algorithm, return statement is used.

In [278]:
def times(x,y):
    z = x*y
    return z

The above defined **times( )** function accepts two arguements and return the variable z which contains the result of the product of the two arguements

In [279]:
c = times(4,5)
print(c)

20


The z value is stored in variable c and can be used for further operations.

Instead of declaring another variable the entire statement itself can be used in the return statement as shown.

In [280]:
def times(x,y):
    '''This multiplies the two input arguments'''
    return x*y

In [281]:
c = times(4,5)
print(c)

20


Since the **times( )** is now defined, we can document it as shown above. This document is returned whenever **times( )** function is called under **help( )** function.

In [282]:
help(times)

Help on function times in module __main__:

times(x, y)
    This multiplies the two input arguments



Multiple variable can also be returned, But keep in mind the order.

In [283]:
eglist = [10,50,30,12,6,8,100]

In [284]:
def egfunc(eglist):
    'Function that returns the maximum, minimum, first and last values in a list'
    highest = max(eglist)
    lowest = min(eglist)
    first = eglist[0]
    last = eglist[-1]
    return highest,lowest,first,last

If the function is just called without any variable for it to be assigned to, the result is returned inside a tuple. But if the variables are mentioned then the result is assigned to the variable in a particular order which is declared in the return statement.

In [285]:
egfunc(eglist)

(100, 6, 10, 100)

In [286]:
a,b,c,d = egfunc(eglist)
print(' a =',a,'\n b =',b,'\n c =',c,'\n d =',d)

 a = 100 
 b = 6 
 c = 10 
 d = 100


## Implicit arguments

We use implicit arguments when we want to have a value by default.

In [287]:
def implicitadd(x,y=3):
    return x+y

**implicitadd( )** is a function accepts two arguments but most of the times the first argument needs to be added just by 3. Hence the second argument is assigned the value 3. Here the second argument is implicit.

Now if the second argument is not defined when calling the **implicitadd( )** function then it considered as 3.

In [288]:
implicitadd(4)

7

But if the second argument is specified then this value overrides the implicit value assigned to the argument 

In [289]:
implicitadd(4,4)

8

 <div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b >  Write a Python function to multiply all the numbers in a list </div>

In [290]:
# Your code here

The factorial of a non-negative integer n, denoted by $n!$, is the product of all positive integers less than or equal to n:


$$
n! = n \cdot(n-1) \cdot (n-2) \cdots 3 \cdot 2 \cdot 1
$$

<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b > Write a Python function to calculate the factorial of a number (a non-negative integer). The function accepts the number as an argument. </div>

In [291]:
# Your code here

<div class = "alert alert-info" style = "border-radius:10px" ><b>EXERCISE:</b > Write a Python function that takes a list and returns a new list with unique elements of the first list. </div>

In [292]:
# Your code here

# NUMPY

Python is not designed specifically for mathematical and scientific computing.
In particular, Python lists are very flexible containers, but they are poorly suited to efficiently represent common mathematical constructs like vectors and matrices. 

Fortunately, the **numpy** package (module) exists. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. Its performance is very good. It is used in almost all numerical computation using Python.

Why not simply use Python lists for computations instead of creating a new array type?

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementating such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).

## Basics of Numpy

To use **numpy** it is needed to import the module:

In [293]:
import numpy as np

## Creating numpy arrays
There are a number of ways to initialize new numpy arrays, for example from

1. A Python list or tuples
2. Using array-generating functions, such as `arange`, `zeros`, etc.
3. Reading data from files

### 1. From a list
For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [294]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [295]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

### 2. Using array-generating functions
For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generates arrays of different forms. Some of the more common are:

**Zeros and Ones**

In [296]:
np.zeros(5, dtype=float)

array([0., 0., 0., 0., 0.])

In [297]:
np.ones(5,dtype=float)

array([1., 1., 1., 1., 1.])

In [298]:
np.zeros((2,3),dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0]])

### arange

In [299]:
x = np.arange(0, 20, 1) # arguments: start, stop, step
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### Creating random arrays

In [300]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

array([[3.05159941e-02, 8.89417830e-04, 8.08400765e-01, 5.32121525e-01,
        5.26027294e-02],
       [9.01064908e-01, 8.56943538e-01, 9.36920130e-01, 3.69879511e-01,
        9.24287711e-01],
       [2.53783843e-01, 7.66152598e-01, 4.29781458e-01, 8.55842193e-01,
        6.32794558e-01],
       [3.98636339e-01, 9.58531434e-01, 1.79432698e-01, 7.12032308e-01,
        2.66773474e-01],
       [5.01423162e-01, 7.02116586e-01, 1.55736580e-02, 7.60727565e-01,
        6.31248638e-01]])

### Manipulating arrays

In [301]:
lst = [10, 20, 30, 40] #python list
arr = np.array([10, 20, 30, 40],dtype='int64') #numpy array
M = np.array([[10, 20, 30, 40],[50, 60, 70, 80]]) #numpy matrix

#### Element indexing

In [302]:
#get the first element of list
lst[0]


10

In [303]:
#get the first element of array
arr[0]

10

In [304]:
# M is a matrix, or a 2 dimensional array, taking two indices 
print(M)
print(M[0,0]) # element from first row first column 
print(M[1,1]) # element from second row second column
print(M[1,2]) 

[[10 20 30 40]
 [50 60 70 80]]
10
60
70


#### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [305]:
A = np.array([1,2,3,4,5])
#slice from second to fourth element, step is one
A[1:3:1]

array([2, 3])

In [306]:
A[:3] # first three elements

array([1, 2, 3])

In [307]:
A[3:] # elements from index 3

array([4, 5])

In [308]:
A[-1] # the last element in the array

5

In [309]:
A[-3:] # the last three elements

array([3, 4, 5])

### Built-in functions

There are many functions to work with numpy arrays. Here we show some of them.

In [310]:
# Sum all elements
np.sum(A)

15

In [311]:
# Mean of all elements
np.mean(A)

3.0

In [312]:
# Maximum
np.max(A)

5

In [313]:
# Minimum
np.min(A)

1

In [314]:
# Sort array
np.sort(A)

array([1, 2, 3, 4, 5])